apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appset
  name: appset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appset
  template:
    metadata:
      labels:
        app: appset
    spec:
      containers:
        - name: test
          image: alpine
          command: ["sh", "-c"]
          args:
            - while true; do echo "$MESSAGE"; sleep 2; done;
          env:
            - name: MESSAGE
              value: "default message"
