apiVersion: v1
kind: Service
metadata:
  name: app-placeholder
  labels:
    app: app-placeholder
spec:
  selector:
    app: app-placeholder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
