apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: app1
spec:
  template:
    spec:
      containers:
        - name: app1
          image: alpine
          env:
            - name: MESSAGE
              value: "hello from app1"
