apiVersion: v1
kind: Service
metadata:
  name: bubble-animation-{{ .Values.color }}
  namespace: bubble-animation
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bubble-animation