apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2
spec:
  template:
    spec:
      containers:
        - name: app2
          env:
            - name: MESSAGE
              value: "hello from app2"
